; ==============================================================================
; CONFIGURE-WINDOWS: Cấu Hình & Tinh Chỉnh Hệ Thống Windows 11
; ==============================================================================

[general]
log_path=C:\Windows\Temp\configure-windows.log

[explorer]
; Hiện đuôi tập tin (.txt, .exe, .ps1...)
show_extensions=true
; Ẩn file ẩn ("HideAll" | "Show")
hidden_items=HideAll
; Mở File Explorer vào This PC thay vì Quick Access ("ThisPC" | "QuickAccess")
launch_to=ThisPC

[taskbar]
; Bật lệnh "End Task" khi chuột phải vào ứng dụng ở Taskbar
end_task=true
; Vị trí căn lề Taskbar ("Left" | "Center")
alignment=Left
; Hộp tìm kiếm trên Taskbar ("Hide" | "Icon" | "Full")
search_mode=Hide
; Bật/Tắt widget thời tiết và tin tức rác ("true" | "false")
widgets=false
; Bật/Tắt nút Task View
taskview=false

[start_menu]
; Tắt gợi ý tìm kiếm Bing trên Start Menu
disable_bing_search=true
; Tắt quảng cáo và gợi ý ứng dụng trên Start Menu
disable_recommendations=true

[debloat]
; Tự động gỡ các ứng dụng rác cài sẵn (Candy Crush, TikTok, Spotify demo, Xbox junk...)
remove_bloatware=true

[system]
; Kích hoạt giao diện tối (Dark Mode) cho cả Hệ thống và Ứng dụng
enable_dark_mode=true
; Tắt dịch vụ thu thập dữ liệu theo dõi (Telemetry & Diagnostics)
disable_telemetry=true
; Ngăn chặn BitLocker tự động khóa ổ đĩa
disable_bitlocker=true
; Kích hoạt gói hiệu năng cao (Ultimate / High Performance Power Plan)
enable_performance_plan=true
